# Site settings
title: Ansible Broker
description: >-
  Welcome to Ansible Broker
#baseurl: ""
url: "http://ansiblebroker.org"

# Build settings
markdown: kramdown
#plugins:
#exclude:

#Social
repo: https://github.com/openshift/ansible-service-broker
youtube: https://www.youtube.com/channel/UC04eOMIMiV06_RSZPb4OOBw
twitter: https://twitter.com/openshift
