# Site settings
title: Ansible Broker
description: >-
  Welcome to Ansible Broker
baseurl: ""
url: "http://ansiblebroker.org"
repo: https://github.com/openshift/ansible-service-broker

# Build settings
markdown: kramdown
#plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
